import os
import random
import re
from moviepy.editor import VideoFileClip, AudioFileClip, TextClip, CompositeVideoClip

def parse_vtt(vtt_file):
    """
    Parses a VTT file and returns a list of dictionaries with start, end, and text.
    """
    with open(vtt_file, 'r', encoding='utf-8') as f:
        content = f.read()

    # Regex to match the timestamps and text in the VTT generated by edge-tts
    # Format usually looks like:
    # 00:00:00.100 --> 00:00:00.500
    # Hello
    
    pattern = re.compile(r'(\d{2}:\d{2}:\d{2}\.\d{3})\s*-->\s*(\d{2}:\d{2}:\d{2}\.\d{3})\n(.*?)(?=\n\n|\Z)', re.DOTALL)
    matches = pattern.findall(content)
    
    subs = []
    for match in matches:
        start_str, end_str, text = match
        
        # Convert timestamp to seconds
        def time_to_sec(t):
            h, m, s = t.split(':')
            sec, ms = s.split('.')
            return int(h) * 3600 + int(m) * 60 + int(sec) + int(ms) / 1000.0
            
        start_sec = time_to_sec(start_str)
        end_sec = time_to_sec(end_str)
        
        subs.append({
            'start': start_sec,
            'end': end_sec,
            'text': text.strip()
        })
        
    return subs

def create_video(audio_path, vtt_path, background_path="assets/background.mp4", output_path="final_video.mp4"):
    """
    Assembles the final video by combining background, audio, and captions.
    """
    print("Assembling final video...")
    
    # Load audio
    audio = AudioFileClip(audio_path)
    audio_duration = audio.duration
    
    # Handle background video
    if not os.path.exists(background_path):
        print(f"Warning: Background video '{background_path}' not found.")
        print("Please place a long gameplay or stock video in the 'assets' folder.")
        print("Using a placeholder solid color background instead.")
        # Create a black background if none exists (for testing)
        from moviepy.editor import ColorClip
        bg_clip = ColorClip(size=(1080, 1920), color=(0, 0, 0), duration=audio_duration)
    else:
        # Load and process actual background video
        bg_clip = VideoFileClip(background_path)
        
        # Make sure background is longer than audio
        if bg_clip.duration < audio_duration:
            print("Background video is shorter than audio. Looping...")
            from moviepy.video.fx.all import loop
            bg_clip = bg_clip.fx(loop, duration=audio_duration)
            
        # Pick a random starting point
        max_start = max(0, bg_clip.duration - audio_duration)
        start_time = random.uniform(0, max_start)
        
        bg_clip = bg_clip.subclip(start_time, start_time + audio_duration)
        
        # Crop to vertical 9:16 (assuming 1080x1920 target, or resizing)
        # We will resize height to 1920, then crop width to 1080 from center
        bg_clip = bg_clip.resize(height=1920)
        w, h = bg_clip.size
        x_center = w / 2
        bg_clip = bg_clip.crop(x1=x_center-540, y1=0, x2=x_center+540, y2=1920)

    # Attach the audio to the background
    final_video = bg_clip.set_audio(audio)
    
    # Generate Subtitles
    print("Generating animated subtitles...")
    subs = parse_vtt(vtt_path)
    
    subtitle_clips = []
    
    # Use a large, bold font for the "viral" look
    # Note: 'Impact' or 'Arial-Bold' usually works. On Linux, might need to specify path.
    font_name = "Impact" if os.name == 'nt' else "Arial-Bold"
    
    for sub in subs:
        # Create text clip. 
        # Adding a black stroke/outline helps it pop against any background.
        txt_clip = TextClip(
            sub['text'], 
            fontsize=120, 
            color='white', 
            font=font_name,
            stroke_color='black',
            stroke_width=5,
            method='caption',
            size=(900, None) # Max width 900px so it doesn't touch edges
        )
        
        # Position in center, set start and end time
        txt_clip = txt_clip.set_position(('center', 'center')).set_start(sub['start']).set_end(sub['end'])
        
        subtitle_clips.append(txt_clip)
        
    # Composite all the subtitle clips over the video
    print("Compositing video...")
    final_video_with_subs = CompositeVideoClip([final_video] + subtitle_clips)
    
    # Write the result to a file
    print("Rendering final MP4 (this may take a while)...")
    os.makedirs(os.path.dirname(output_path), exist_ok=True)
    
    final_video_with_subs.write_videofile(
        output_path, 
        fps=30, 
        codec="libx264", 
        audio_codec="aac",
        threads=4,
        logger=None # Suppress massive progress bars in terminal
    )
    
    # Clean up
    audio.close()
    if isinstance(bg_clip, VideoFileClip):
        bg_clip.close()
    final_video_with_subs.close()
    
    print(f"Video successfully rendered to {output_path}")
    return output_path

if __name__ == "__main__":
    # Test block
    if os.path.exists("temp/audio.mp3") and os.path.exists("temp/subs.vtt"):
        create_video("temp/audio.mp3", "temp/subs.vtt", output_path="temp/test_output.mp4")
